---
config:
  layout: elk
  elk:
    mergeEdges: false
    nodePlacementStrategy: NETWORK_SIMPLEX
  theme: 'redux'
---
flowchart TB
 subgraph ethereum["Ethereum"]
        Gateway(["Quiet Finance"])
        USDC@{ img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/USD_Coin_logo_%28cropped%29.png", pos: "t", w: 60, h: 60, constraint: "on" }
        USDC.in@{ img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/USD_Coin_logo_%28cropped%29.png", pos: "t", w: 60, h: 60, constraint: "on" }

        USDT.eth@{ img: "https://upload.wikimedia.org/wikipedia/commons/0/01/USDT_Logo.png", pos: "t", w: 60, h: 60, constraint: "on"}
        Liquid.eth["Liquid strategies"]@{shape: "docs"}
        ILliquid.eth["Illiquid strategies"]@{shape: "st-rect"}

        USDC.in --> Gateway --> USDC
        USDC -->|"Swap (via 1inch)"| USDT.eth
        USDC & USDT.eth .-> Liquid.eth & ILliquid.eth
  end
 subgraph l2["L2 chain (e.g. Base)"]
        USDC.l2@{ img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/USD_Coin_logo_%28cropped%29.png", pos: "t", w: 60, h: 60, constraint: "on" }
        USDT.l2@{ img: "https://upload.wikimedia.org/wikipedia/commons/0/01/USDT_Logo.png", pos: "t", w: 60, h: 60, constraint: "on"}
        Liquid.l2["Liquid strategies"]@{shape: "docs"}
        ILliquid.l2["Illiquid strategies"]@{shape: "st-rect"}

        USDC.l2 --> Liquid.l2 & ILliquid.l2
        USDT.l2 --> Liquid.l2 & ILliquid.l2
  end
 subgraph evm["EVM chain (e.g HyperEVM)"]
        USDC.evm@{ img: "https://upload.wikimedia.org/wikipedia/commons/c/ca/USD_Coin_logo_%28cropped%29.png", pos: "t", w: 60, h: 60, constraint: "on" }
        USDT.evm@{ img: "https://upload.wikimedia.org/wikipedia/commons/0/01/USDT_Logo.png", pos: "t", w: 60, h: 60, constraint: "on"}
        Liquid.evm["Liquid strategies"]@{shape: "docs"}
        ILliquid.evm["Illiquid strategies"]@{shape: "st-rect"}

        USDC.evm & USDT.evm ..-> Liquid.evm & ILliquid.evm
  end

  USDC -->|Via CCTP| USDC.l2 & USDC.evm
  USDT.eth -->|Via USDT0| USDT.l2 & USDT.evm

  sqUSD@{ img: "https://raw.githubusercontent.com/quiet-finance/brand-assets/refs/heads/main/sqUSD.png", pos: "b", w: 60, h: 60, constraint: "on", "label": "sqUSD" }
  Liquid.eth & ILliquid.eth & Liquid.evm & ILliquid.evm & Liquid.l2 & ILliquid.l2 .->|Yield| sqUSD
